// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBuwpkogVlERtnU_8d0K3c2qDbO5g3kVw',
    appId: '1:264070430306:web:9e2e4787299d65b08e1b3b',
    messagingSenderId: '264070430306',
    projectId: 'flutter-chat-app-29acc',
    authDomain: 'flutter-chat-app-29acc.firebaseapp.com',
    storageBucket: 'flutter-chat-app-29acc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWu2tv339-ormYGXrvyBLp-uc3O3Yma0Y',
    appId: '1:264070430306:android:d011263c5e7f1c448e1b3b',
    messagingSenderId: '264070430306',
    projectId: 'flutter-chat-app-29acc',
    storageBucket: 'flutter-chat-app-29acc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJP1Zc00Ltv5OAxpQoRSXXanmwrYq4uJ8',
    appId: '1:264070430306:ios:35fc7957fe2420f98e1b3b',
    messagingSenderId: '264070430306',
    projectId: 'flutter-chat-app-29acc',
    storageBucket: 'flutter-chat-app-29acc.appspot.com',
    iosBundleId: 'com.example.cipicapachat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJP1Zc00Ltv5OAxpQoRSXXanmwrYq4uJ8',
    appId: '1:264070430306:ios:9301dc63332fc5c48e1b3b',
    messagingSenderId: '264070430306',
    projectId: 'flutter-chat-app-29acc',
    storageBucket: 'flutter-chat-app-29acc.appspot.com',
    iosBundleId: 'com.example.cipicapachat.RunnerTests',
  );
}
